%____________________________________
%
% Author        - Vitamin-C
%
% Status        - Supplementary to impedance_with_inductance.m
%
% Description   - Mathematical representation of features of the examined
%                 impedance spectra.
%_____________________________________

function newby=newby(c,rads,Zr,Zim)
newby=100000*sum((1./sqrt((Zr).^2+(Zim).^2)).*...
    ((Zr-(c(1)+(((c(3)*rads.^(-c(4))+c(2)*cos(c(4)*pi()/2)).*...
    (c(2)*c(3)*rads.^(-c(4))))./...
    ((c(3)*rads.^(-c(4))+c(2)*cos(c(4)*pi()/2)).^2+...
    (c(2)*sin(c(4)*pi()/2)).^2))+...
    (((c(6)*rads.^(-c(7))+c(5)*cos(c(7)*pi()/2)).*...
    (c(5)*c(6)*rads.^(-c(7))))./...
    ((c(6)*rads.^(-c(7))+c(5)*cos(c(7)*pi()/2)).^2+...
    (c(5)*sin(c(7)*pi()/2)).^2))+...
    (c(8)*rads.^(-c(9))*cos(c(9)*pi()/2)))).^2+...
    (-Zim-((-((c(2)*sin(c(4)*pi()/2)).*...
    (c(2)*c(3)*rads.^(-c(4))))./...
    ((c(3)*rads.^(-c(4))+c(2)*cos(c(4)*pi()/2)).^2+...
    (c(2)*sin(c(4)*pi()/2)).^2))+...
    (-((c(5)*sin(c(7)*pi()/2)).*...
    (c(5)*c(6)*rads.^(-c(7))))./...
    ((c(6)*rads.^(-c(7))+c(5)*cos(c(7)*pi()/2)).^2+...
    (c(5)*sin(c(7)*pi()/2)).^2))+...
    (-(c(8)*rads.^(-c(9))*sin(c(9)*pi()/2))))).^2));
end